### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by gpx1000**
Closes https://github.com/KhronosGroup/Vulkan-Site/issues/27

### CODE REVIEW

**Comment by KhronosWebservices** [comment]
It would be good to add a complete set of headers and icons to ensure we get full coverage across all devices. Headers would be along the lines of:

```
<link rel="apple-touch-icon" sizes="180x180" href="{{{uiRootPath}}}/img/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="{{{uiRootPath}}}/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="{{{uiRootPath}}}/img/favicon-16x16.png">
<link rel="manifest" href="{{{uiRootPath}}}/img/site.webmanifest">
<link rel="mask-icon" href="{{{uiRootPath}}}/img/safari-pinned-tab.svg" color="#a41e22">
<meta name="msapplication-TileColor" content="#ffc40d">
<meta name="theme-color" content="#ffffff">
```

Marty now has the complete icon set to match these headers.

**Comment by gpx1000** [comment]
the latest should have requested changes

**Comment by oddhack** [comment]
@gpx1000 I added the same set of progress milestones that we use on the Vulkan spec to help progress PRs/issues here. If this is ready to go you can change the milestone to 'Signed off  to merge' (or just accept it yourself).

**Comment by gpx1000** [comment]
It wont let me sign off or change the milestone.

**Comment by oddhack** [comment]
> It wont let me sign off or change the milestone.

You should have Admin access to this and Vulkan-Site repos now. Also I added the Vulkan team with Write access to both.

**Comment by oddhack** [comment]
Will this close https://github.com/KhronosGroup/Vulkan-Site/issues/27 ? Also, needs conflict resolved before merging.

**Comment by marty-johnson59** [comment]
This will close Sascha's issue (#27).  

Note, we also need the new process to pick up any changes to the other repos (tutorial, guide, samples) each time the spec is published.  I think the current published version is out of date.  Is that part of your plan moving forward?

**Comment by oddhack** [comment]
> Note, we also need the new process to pick up any changes to the other repos (tutorial, guide, samples) each time the spec is published. I think the current published version is out of date. Is that part of your plan moving forward?

It is.

**Pull request merged**
